version: '3'

services:
  prometheus:
    image: prom/prometheus:v2.51.2
    ports:
      - 9090:9090
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus-data:/prometheus
    command: --web.enable-lifecycle  --config.file=/etc/prometheus/prometheus.yml
    network_mode: bridge
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  prometheus-data:
