[package]
name = "distrans-fileindex"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust-crypto = "0.2"
thiserror = "1.0"
tokio = { version = "1.33", features = ["fs", "io-util"] }
