name: Test

on:
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --verbose --workspace
      - name: Run unit tests
        run: cargo test --verbose --workspace
      - name: Run integration tests
        run: ./scripts/e2e_seed_fetch.sh
