name: Test

on:
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install capnproto & protobuf for linux
      run: ./tools/install_ubuntu.sh
    - name: Build
      run: cargo build --verbose --workspace
    - name: Run tests
      run: cargo test --verbose --workspace
